### ISSUE TITLE
[Add Project]: Kotlin Casper Client SDK

### ISSUE THREAD

**Issue by tqhuy2018** [casper-ecosystem/casperecosystem-io-data#49]
### Name

Kotlin Casper Client SDK

### Website

https://github.com/tqhuy2018/Casper-Kotlin-sdk

### Tag

SDK

### Project Description

Implement a Casper Kotlin SDK to interact with the Casper network.

**Comment by devendran-m** [comment]
Hi @tqhuy2018 ,

Could you let me know if the SDK is in line with the latest casper-node that went in and whether they are in alignment with upcoming casper-node releases, please?

**Comment by tqhuy2018** [comment]
This version of Kotlin SDK is in line with the latest casper-node that went in. You can see the test result in the picture.

Whether it is compatible with casper-node in the future or not, it is necessary to consider whether you change the sending Json data structure (for put_deploy RPC method) and returned Json data structure (for other RPC methods) or not. If the upcoming version changes, we will need to update the SDK.

![z4277474690379_d07cbf8c5470806dcf0758e3e86cf9d1](https://user-images.githubusercontent.com/87941180/233024906-a7d0a75b-f5a4-4755-9b52-464f159952ae.jpg)
