### ISSUE TITLE
[Add Project]: CSPR.market

### ISSUE THREAD

**Issue by mrkara** [casper-ecosystem/casperecosystem-io-data#81]
### Name

CSPR.market

### Website

cspr.market

### Twitter

@CsprMarket

### Tag

NFT

### Contact

hello@make.services

### Project's Contract Hashes on Casper Mainnet

31cc023b17c903a963ec60eab96a60f1fa37cb74b4b3bafc91a441e0e9d70f97,
0b0508bf0f4cfd0689cbfa1e65a1ad5a3732c36ee2928f9d78701ebdc8983825

### Project's Contract Hashes on Casper Testnet

hash-154ff59b5f9feec42d3a418058d66badcb2121dc3ffb2e3cf92596bf5aafbc88,
hash-a7b2de3119f20c32ec19a103359e7b2942159a3198bde29687b497c22a9d27bc

### Project Description

CSPR.market is your ultimate destination for exploring/buying /selling NFTs on Casper Network.

**Highlights:**
- State of the Art UX & UI
- Supports the brand new [Casper Wallet](https://casperwallet.io/)
- Compatible with CEP-78 and CEP-47
- Largest assortment of NFTs: Digital arts, in-game items, CSPR names, IPs and more.
- On-chain royalties
- Exclusive listing of many projects

[Join us on Telegram](https://t.me/CSPRhub) for the latest news about CSPR.market and other apps from the CSPR Product Suite - powered by [MAKE](https://make.services/).

**Comment by devendran-m** [comment]
Thanks, @mrkara , working on it. It will be completed by Monday - 24th July

**Comment by devendran-m** [comment]
Hi @mrkara , 
Do you have a logo that you can share please?
